name: Publish Package to Azure Artifacts

on:
  push:
    branches:
      - main  # triggers on any push or merge into main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org" # fallback for public packages

      # 3. Authenticate to Azure Artifacts
      - name: Authenticate to Azure Artifacts
        run: |
          # Set registry for your scoped package
          npm config set @${{ secrets.AZURE_ORG }}:registry https://pkgs.dev.azure.com/${{ secrets.AZURE_ORG }}/${{ secrets.AZURE_PROJECT }}/_packaging/${{ secrets.AZURE_FEED }}/npm/registry/
          # Set auth token for Azure feed
          npm config set //pkgs.dev.azure.com/${{ secrets.AZURE_ORG }}/${{ secrets.AZURE_PROJECT }}/_packaging/${{ secrets.AZURE_FEED }}/npm/registry/:_authToken=${{ secrets.AZURE_NPM_TOKEN }}

      # 4. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 5. Build the package
      - name: Build
        run: yarn build

      # 6. Publish to Azure Artifacts
      - name: Publish to Azure Artifacts
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AZURE_NPM_TOKEN }}
